name: Windows CMake Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v4
      
      - name: Setup Mesa3D (Software OpenGL)
        uses: ssciwr/setup-mesa-dist-win@v2

      - name: Configure CMake
        run: |
          cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: |
          cmake --build build --config ${{env.BUILD_TYPE}} --parallel

      - name: List build outputs
        run: |
          dir "bin\Debug-x64" -Recurse

      - name: Run Unit Tests
        run: |
          .\bin\Debug-x64\Tests\PillarTests.exe --gtest_output=xml:test-results.xml
        env:
          # Ensure Mesa is used for OpenGL
          GALLIUM_DRIVER: llvmpipe

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        if: always()
        with:
          files: test-results.xml

      # Flaky so commenting out for now
      # - name: Smoke Test (Run Sandbox for a few seconds)
      #   run: |
      #     $p = Start-Process -FilePath .\bin\Debug-x64\Sandbox\SandboxApp.exe -PassThru
      #     Start-Sleep -Seconds 3
      #     Stop-Process -Id $p.Id -ErrorAction Stop
